#config test
config:
    address: 泰兴市马店镇
    tel: 18112996639

name: configTest


#redis
redis:
    cache:
        clusterNodes: 121.42.253.157:7000
        commandTimeout: 1000
        expireSeconds: 120


#mybatis
jdbc:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.42.253.157:3309/db_fun
    username: root
    password: 123456
mybatis:
    typeAliasesPackage: com.domain
    mapperLocations: classpath:mapper/*.xml



#spring:
#    datasource:
#        name: test
#        url: jdbc:mysql://121.42.253.157:3309/db_fun
#        username: root
#        password: 123456
#        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        filters: stat
#        maxActive: 20
#        initialSize: 1
#        maxWait: 60000
#        minIdle: 1
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: select 'x'
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxOpenPreparedStatements: 20